import type { Task, Document, Part, StockMovement, Organization, Membership } from '../types';

const NOW = new Date().toISOString();
const YESTERDAY = new Date(Date.now() - 86400000).toISOString();
const NEXT_WEEK = new Date(Date.now() + 7 * 86400000).toISOString();
const NEXT_MONTH = new Date(Date.now() + 30 * 86400000).toISOString();

export const DEMO_ORG: Organization = {
  id: 'demo-org-001',
  name: 'Garage Dupont & Fils',
  slug: 'garage-dupont',
  billing_status: 'active',
  created_at: YESTERDAY,
};

export const DEMO_MEMBERSHIP: Membership = {
  id: 'demo-member-001',
  organization_id: 'demo-org-001',
  user_id: 'demo-user-001',
  role: 'owner',
  created_at: YESTERDAY,
};

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-001',
    organization_id: 'demo-org-001',
    title: 'Révision 15 000 km — Renault Clio IV',
    description: 'Vidange moteur, filtre à huile, filtre habitacle, filtre à air. Vérification niveaux.',
    status: 'in_progress',
    priority: 'high',
    due_date: NEXT_WEEK,
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: NOW,
  },
  {
    id: 'task-002',
    organization_id: 'demo-org-001',
    title: 'Changement plaquettes avant — BMW 320d',
    description: 'Plaquettes Ferodo DS3000. Vérifier disques.',
    status: 'todo',
    priority: 'medium',
    due_date: NEXT_WEEK,
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'task-003',
    organization_id: 'demo-org-001',
    title: 'Diagnostic voyant moteur — Peugeot 3008',
    description: 'Lecture défauts OBD2. Client signale perte de puissance.',
    status: 'todo',
    priority: 'high',
    due_date: NOW,
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'task-004',
    organization_id: 'demo-org-001',
    title: 'Vidange + filtre — Toyota Yaris',
    description: 'Huile moteur 5W30 — 3.5L. Filtre mann.',
    status: 'done',
    priority: 'low',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: NOW,
  },
  {
    id: 'task-005',
    organization_id: 'demo-org-001',
    title: 'Remplacement courroie distribution — Citroën C5',
    description: 'Kit complet Gates. Pompe à eau à vérifier.',
    status: 'todo',
    priority: 'high',
    due_date: NEXT_MONTH,
    archived_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const DEMO_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    organization_id: 'demo-org-001',
    title: 'Facture fournitures Novembre',
    category: 'invoice',
    notes: 'Fournisseur Auto Distribution. Ref: FAC-2024-1187.',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'doc-002',
    organization_id: 'demo-org-001',
    title: 'Bon commande pièces Bosch',
    category: 'receipt',
    notes: 'Bougies, filtres, liquide de frein.',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'doc-003',
    organization_id: 'demo-org-001',
    title: 'Manuel technique Renault Clio IV',
    category: 'manual',
    notes: 'Chapitre moteur 1.5 dCi 90ch.',
    archived_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'doc-004',
    organization_id: 'demo-org-001',
    title: 'Bon de livraison TotalEnergies',
    category: 'delivery',
    notes: 'Huile moteur 5W30, 20L × 3 bidons.',
    archived_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const DEMO_PARTS: Part[] = [
  {
    id: 'part-001',
    organization_id: 'demo-org-001',
    name: 'Filtre à huile Mann W712/95',
    reference: 'W712/95',
    quantity: 12,
    alert_threshold: 3,
    unit: 'pièce',
    location: 'Étagère A1',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'part-002',
    organization_id: 'demo-org-001',
    name: 'Plaquettes avant Ferodo DS3000',
    reference: 'FCP1664H',
    quantity: 2,
    alert_threshold: 2,
    unit: 'jeu',
    location: 'Étagère B2',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: NOW,
  },
  {
    id: 'part-003',
    organization_id: 'demo-org-001',
    name: 'Liquide de frein DOT 4 — 1L',
    reference: 'DOT4-1L',
    quantity: 6,
    alert_threshold: 2,
    unit: 'bouteille',
    location: 'Étagère C3',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'part-004',
    organization_id: 'demo-org-001',
    name: 'Bougies NGK BKR6E',
    reference: 'BKR6E',
    quantity: 20,
    alert_threshold: 8,
    unit: 'pièce',
    location: 'Étagère A3',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'part-005',
    organization_id: 'demo-org-001',
    name: 'Courroie distribution Gates',
    reference: 'K015483XS',
    quantity: 1,
    alert_threshold: 1,
    unit: 'pièce',
    location: 'Étagère D1',
    archived_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'part-006',
    organization_id: 'demo-org-001',
    name: 'Huile moteur 5W30 TotalEnergies',
    reference: '5W30-5L',
    quantity: 8,
    alert_threshold: 3,
    unit: 'bidon 5L',
    location: 'Sol zone fluides',
    archived_at: null,
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
];

export const DEMO_MOVEMENTS: StockMovement[] = [
  {
    id: 'mov-001',
    organization_id: 'demo-org-001',
    part_id: 'part-001',
    type: 'in',
    quantity: 5,
    reason: 'Réapprovisionnement commande Bosch',
    created_at: YESTERDAY,
  },
  {
    id: 'mov-002',
    organization_id: 'demo-org-001',
    part_id: 'part-001',
    type: 'out',
    quantity: 1,
    reason: 'Révision Toyota Yaris',
    created_at: NOW,
  },
  {
    id: 'mov-003',
    organization_id: 'demo-org-001',
    part_id: 'part-002',
    type: 'out',
    quantity: 2,
    reason: 'BMW 320d — plaquettes avant',
    created_at: NOW,
  },
];
