$root = "C:\Users\matti\atelier-logistique"

$b64 = "aW1wb3J0ICdyZWFjdC1uYXRpdmUtdXJsLXBvbHlmaWxsL2F1dG8nOwppbXBvcnQgeyByZWdpc3RlclJvb3RDb21wb25lbnQgfSBmcm9tICdleHBvJzsKaW1wb3J0IEFwcCBmcm9tICcuL0FwcCc7CgpyZWdpc3RlclJvb3RDb21wb25lbnQoQXBwKTsK"
$bytes = [System.Convert]::FromBase64String($b64)
[System.IO.File]::WriteAllBytes("$root\index.ts", $bytes)
Write-Host "OK index.ts"

$b64 = "aW1wb3J0ICdyZWFjdC1uYXRpdmUtdXJsLXBvbHlmaWxsL2F1dG8nOwppbXBvcnQgeyBjcmVhdGVDbGllbnQsIFN1cGFiYXNlQ2xpZW50IH0gZnJvbSAnQHN1cGFiYXNlL3N1cGFiYXNlLWpzJzsKaW1wb3J0IEFzeW5jU3RvcmFnZSBmcm9tICdAcmVhY3QtbmF0aXZlLWFzeW5jLXN0b3JhZ2UvYXN5bmMtc3RvcmFnZSc7Cgpjb25zdCBzdXBhYmFzZVVybCA9IHByb2Nlc3MuZW52LkVYUE9fUFVCTElDX1NVUEFCQVNFX1VSTCA/PyAnJzsKY29uc3Qgc3VwYWJhc2VBbm9uS2V5ID0gcHJvY2Vzcy5lbnYuRVhQT19QVUJMSUNfU1VQQUJBU0VfQU5PTl9LRVkgPz8gJyc7CgpleHBvcnQgY29uc3QgaXNTdXBhYmFzZUNvbmZpZ3VyZWQgPQogIHN1cGFiYXNlVXJsLnN0YXJ0c1dpdGgoJ2h0dHBzOi8vJykgJiYgc3VwYWJhc2VBbm9uS2V5Lmxlbmd0aCA+IDIwOwoKbGV0IF9jbGllbnQ6IFN1cGFiYXNlQ2xpZW50IHwgbnVsbCA9IG51bGw7CgpleHBvcnQgZnVuY3Rpb24gZ2V0U3VwYWJhc2UoKTogU3VwYWJhc2VDbGllbnQgewogIGlmICghaXNTdXBhYmFzZUNvbmZpZ3VyZWQpIHsKICAgIHRocm93IG5ldyBFcnJvcignU3VwYWJhc2Ugbm9uIGNvbmZpZ3Vyw6kg4oCUIG1vZGUgZMOpbW8gYWN0aWYuJyk7CiAgfQogIGlmICghX2NsaWVudCkgewogICAgX2NsaWVudCA9IGNyZWF0ZUNsaWVudChzdXBhYmFzZVVybCwgc3VwYWJhc2VBbm9uS2V5LCB7CiAgICAgIGF1dGg6IHsKICAgICAgICBzdG9yYWdlOiBBc3luY1N0b3JhZ2UsCiAgICAgICAgYXV0b1JlZnJlc2hUb2tlbjogdHJ1ZSwKICAgICAgICBwZXJzaXN0U2Vzc2lvbjogdHJ1ZSwKICAgICAgICBkZXRlY3RTZXNzaW9uSW5Vcmw6IGZhbHNlLAogICAgICAgIGZsb3dUeXBlOiAncGtjZScsCiAgICAgIH0sCiAgICAgIGdsb2JhbDogewogICAgICAgIGhlYWRlcnM6IHsKICAgICAgICAgICd4LW15LWN1c3RvbS1oZWFkZXInOiAnYXRlbGllci1sb2dpc3RpcXVlJywKICAgICAgICB9LAogICAgICB9LAogICAgfSk7CiAgfQogIHJldHVybiBfY2xpZW50Owp9CgpleHBvcnQgY29uc3Qgc3VwYWJhc2UgPSBuZXcgUHJveHkoe30gYXMgU3VwYWJhc2VDbGllbnQsIHsKICBnZXQoX3RhcmdldCwgcHJvcCkgewogICAgcmV0dXJuIGdldFN1cGFiYXNlKClbcHJvcCBhcyBrZXlvZiBTdXBhYmFzZUNsaWVudF07CiAgfSwKfSk7Cg=="
$bytes = [System.Convert]::FromBase64String($b64)
[System.IO.File]::WriteAllBytes("$root\src\lib\supabase.ts", $bytes)
Write-Host "OK src\lib\supabase.ts"

Write-Host "Fix Android auth appliqué !" -ForegroundColor Green